services:
  docker_isbg:
    image: hypopheralcus/isbg:latest
    environment:
      TZ: Europe/Berlin
      CRON_HOUR: 1
      CRON_MINUTE: 30
      HAM_BATCH_SIZE: 50
      SPAM_BATCH_SIZE: 200
      FILTER_BATCH_SIZE: 50
      DETAILED_LOGGING: "true"
      LIST_FOLDERS: "true"
    volumes:
      - spamassassinVol:/var/lib/spamassassin
      - accounts:/var/lib/mailaccounts:ro

volumes:
  spamassassinVol:
    external: true
  accounts:
    external: true
